repos:
  # === HOOKS THAT MODIFY ===
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black
        language_version: python
        args:
          - "-l 80"
          - "--preview"

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args:
          - "--profile=black"
          - "--line-length=80"

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args:
          - "--in-place"
          - "--remove-all-unused-imports"
          - "--remove-unused-variables"
          - "--ignore-init-module-imports"

  - repo: https://github.com/qoomon/git-conventional-commits
    rev: v2.6.5
    hooks:
      - id: conventional-commits
        stages:
          - commit-msg

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        additional_dependencies:
          - types-all

  # === CHECK FINAL RESULT ===
  - repo: https://github.com/pylint-dev/pylint
    rev: v3.0.3
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types:
          - python
        args:
          - "--fail-under=8"
          - "--disable=missing-module-docstring"
          - "--disable=missing-class-docstring"
          - "--disable=missing-function-docstring"
          - "--disable=import-error"
          - "--disable=too-few-public-methods"
